---
- name: Add APT key
  apt_key:
    id: E52529D4
    keyserver: keyserver.ubuntu.com

# Подключаем репозиторий с пакетами mongodb
- name: Add  repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse
    state: present
  tags: mongo

# Выполним установку пакета
- name: Install mongodb package
  apt:
    name: mongodb-org
    state: present
  tags: mongo

# Включаем сервис
- name: Configure service supervisor
  systemd:
    name: mongod
    enabled: yes
  tags: mongo
